//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VETCLINIC_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string PostalAddress { get; set; }
        public string PetName { get; set; }
        public string AnimalType { get; set; }
        public string Breed { get; set; }
        public string OwnerName { get; set; }
        public string BirthDate { get; set; }
        public string AppointmentDate { get; set; }
    }
}
